name: Chrome Browser
version: "2026.10.04.03"
slug: chrome_browser
image: ghcr.io/drmogie/{arch}-addon-chrome-browser
description: A Chromium browser you use from a web page, running on your Home Assistant server
url: https://github.com/drmogie/chrome-browser-addon
arch:
  - amd64
  - aarch64
init: false
startup: application
boot: auto
ports:
  3000/tcp: 3010
  3001/tcp: 3011
ports_description:
  3000/tcp: Browser web page (HTTP). Host port 3010
  3001/tcp: Browser web page (HTTPS, self-signed). Host port 3011
webui: https://[HOST]:[PORT:3001]
map:
  - addon_config:rw
panel_icon: mdi:google-chrome
options:
  timezone: "America/Los_Angeles"
  username: ""
  password: ""
  start_url: ""
  proxy_server: ""
  extra_chrome_flags: "--disable-dev-shm-usage"
schema:
  timezone: str
  username: str?
  password: password?
  start_url: str?
  proxy_server: str?
  extra_chrome_flags: str?
